spring:
  cloud:
    gateway:
      discovery:
        locator:
          ###允许通过注册中心获取地址调用，默认是false
          enabled: true
          lower-case-service-id: true  #开启后服务名可以小写
      ###路由策略
      routes:
        ###根据我们的服务名称查找地址实现调用
        - id: gatewayp
          ####转发feign-member，注册到nacos的服务
          #uri: lb://feign-member/  lb代表从注册中心获取服务
          uri: lb://nacos-provider/provider
          #filters:
          #- StripPrefix=1  #去掉Path中前n个   请求/name/bar/foo，去除掉前面两个前缀之后，最后转发到目标服务的路径为/foo
          ###匹配规则
          predicates:
            - Path=/provider/**    #/** 的吗、内容不会省略 没有服务依然会报404

        - id: testgateway
          #- Path=/provider/**  测试 访问gateway ip+端口
          uri: https://www.baidu.com/
          predicates:
            - Path=/**     #访问 gatewayip+端口/path  跳转  uri
            #- Query=baz     游览器访问 192.168.0.195:28080？baz=""(=任意内容) 跳转到  https://www.baidu.com/
        #多个id 多个匹配规则
    #        - id: common-auth
    #              #访问服务，注册中心中的服务名common-auth
    #          uri: lb://common-auth
    #            predicates:
    #                  #访问地址
    #              - Path=http://